//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DominioEntidades.SisReservas
{
    
    public partial class O_LISTAR_ASIENTO_COMPLETO : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public Nullable<decimal> ID_ASIENTO_RUTA
        {
            get { return _iD_ASIENTO_RUTA; }
            set
            {
                if (_iD_ASIENTO_RUTA != value)
                {
                    OnComplexPropertyChanging();
                    _iD_ASIENTO_RUTA = value;
                    OnPropertyChanged("ID_ASIENTO_RUTA");
                }
            }
        }
        private Nullable<decimal> _iD_ASIENTO_RUTA;
    
        [DataMember]
        public Nullable<decimal> ID_RUTA
        {
            get { return _iD_RUTA; }
            set
            {
                if (_iD_RUTA != value)
                {
                    OnComplexPropertyChanging();
                    _iD_RUTA = value;
                    OnPropertyChanged("ID_RUTA");
                }
            }
        }
        private Nullable<decimal> _iD_RUTA;
    
        [DataMember]
        public Nullable<decimal> ID_ESTADO_ASIENTO
        {
            get { return _iD_ESTADO_ASIENTO; }
            set
            {
                if (_iD_ESTADO_ASIENTO != value)
                {
                    OnComplexPropertyChanging();
                    _iD_ESTADO_ASIENTO = value;
                    OnPropertyChanged("ID_ESTADO_ASIENTO");
                }
            }
        }
        private Nullable<decimal> _iD_ESTADO_ASIENTO;
    
        [DataMember]
        public string ASIENTO_RUTA
        {
            get { return _aSIENTO_RUTA; }
            set
            {
                if (_aSIENTO_RUTA != value)
                {
                    OnComplexPropertyChanging();
                    _aSIENTO_RUTA = value;
                    OnPropertyChanged("ASIENTO_RUTA");
                }
            }
        }
        private string _aSIENTO_RUTA;
    
        [DataMember]
        public Nullable<decimal> AUD_ESTADO
        {
            get { return _aUD_ESTADO; }
            set
            {
                if (_aUD_ESTADO != value)
                {
                    OnComplexPropertyChanging();
                    _aUD_ESTADO = value;
                    OnPropertyChanged("AUD_ESTADO");
                }
            }
        }
        private Nullable<decimal> _aUD_ESTADO;
    
        [DataMember]
        public Nullable<System.DateTime> FECHA_REGISTRO
        {
            get { return _fECHA_REGISTRO; }
            set
            {
                if (_fECHA_REGISTRO != value)
                {
                    OnComplexPropertyChanging();
                    _fECHA_REGISTRO = value;
                    OnPropertyChanged("FECHA_REGISTRO");
                }
            }
        }
        private Nullable<System.DateTime> _fECHA_REGISTRO;
    
        [DataMember]
        public Nullable<decimal> ID_ASIENTO
        {
            get { return _iD_ASIENTO; }
            set
            {
                if (_iD_ASIENTO != value)
                {
                    OnComplexPropertyChanging();
                    _iD_ASIENTO = value;
                    OnPropertyChanged("ID_ASIENTO");
                }
            }
        }
        private Nullable<decimal> _iD_ASIENTO;
    
        [DataMember]
        public string ESTADO_ASIENTO
        {
            get { return _eSTADO_ASIENTO; }
            set
            {
                if (_eSTADO_ASIENTO != value)
                {
                    OnComplexPropertyChanging();
                    _eSTADO_ASIENTO = value;
                    OnPropertyChanged("ESTADO_ASIENTO");
                }
            }
        }
        private string _eSTADO_ASIENTO;
    
        [DataMember]
        public string NUMERO
        {
            get { return _nUMERO; }
            set
            {
                if (_nUMERO != value)
                {
                    OnComplexPropertyChanging();
                    _nUMERO = value;
                    OnPropertyChanged("NUMERO");
                }
            }
        }
        private string _nUMERO;
    
        [DataMember]
        public string TIPO_ASIENTO
        {
            get { return _tIPO_ASIENTO; }
            set
            {
                if (_tIPO_ASIENTO != value)
                {
                    OnComplexPropertyChanging();
                    _tIPO_ASIENTO = value;
                    OnPropertyChanged("TIPO_ASIENTO");
                }
            }
        }
        private string _tIPO_ASIENTO;
    
        [DataMember]
        public Nullable<decimal> ID_TIPO_ASIENTO
        {
            get { return _iD_TIPO_ASIENTO; }
            set
            {
                if (_iD_TIPO_ASIENTO != value)
                {
                    OnComplexPropertyChanging();
                    _iD_TIPO_ASIENTO = value;
                    OnPropertyChanged("ID_TIPO_ASIENTO");
                }
            }
        }
        private Nullable<decimal> _iD_TIPO_ASIENTO;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, O_LISTAR_ASIENTO_COMPLETO complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("El parámetro de cadena no puede ser NULL ni estar vacío.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_ASIENTO_RUTA", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_ASIENTO_RUTA);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_RUTA", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_RUTA);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_ESTADO_ASIENTO", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_ESTADO_ASIENTO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ASIENTO_RUTA", parentPropertyName), complexObject == null ? null : (object)complexObject.ASIENTO_RUTA);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AUD_ESTADO", parentPropertyName), complexObject == null ? null : (object)complexObject.AUD_ESTADO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.FECHA_REGISTRO", parentPropertyName), complexObject == null ? null : (object)complexObject.FECHA_REGISTRO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_ASIENTO", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_ASIENTO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ESTADO_ASIENTO", parentPropertyName), complexObject == null ? null : (object)complexObject.ESTADO_ASIENTO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.NUMERO", parentPropertyName), complexObject == null ? null : (object)complexObject.NUMERO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.TIPO_ASIENTO", parentPropertyName), complexObject == null ? null : (object)complexObject.TIPO_ASIENTO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_TIPO_ASIENTO", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_TIPO_ASIENTO);
        }

        #endregion

    }
}
