//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DominioEntidades.SisReservas
{
    
    public partial class O_RESULTADO : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public Nullable<decimal> ID_TABLA
        {
            get { return _iD_TABLA; }
            set
            {
                if (_iD_TABLA != value)
                {
                    OnComplexPropertyChanging();
                    _iD_TABLA = value;
                    OnPropertyChanged("ID_TABLA");
                }
            }
        }
        private Nullable<decimal> _iD_TABLA;
    
        [DataMember]
        public string MENSAJE_ERROR
        {
            get { return _mENSAJE_ERROR; }
            set
            {
                if (_mENSAJE_ERROR != value)
                {
                    OnComplexPropertyChanging();
                    _mENSAJE_ERROR = value;
                    OnPropertyChanged("MENSAJE_ERROR");
                }
            }
        }
        private string _mENSAJE_ERROR;
    
        [DataMember]
        public Nullable<decimal> RESULTADO
        {
            get { return _rESULTADO; }
            set
            {
                if (_rESULTADO != value)
                {
                    OnComplexPropertyChanging();
                    _rESULTADO = value;
                    OnPropertyChanged("RESULTADO");
                }
            }
        }
        private Nullable<decimal> _rESULTADO;

        #endregion
        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, O_RESULTADO complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("El parámetro de cadena no puede ser NULL ni estar vacío.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_TABLA", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_TABLA);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MENSAJE_ERROR", parentPropertyName), complexObject == null ? null : (object)complexObject.MENSAJE_ERROR);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.RESULTADO", parentPropertyName), complexObject == null ? null : (object)complexObject.RESULTADO);
        }

        #endregion
    }
}
