//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DominioEntidades.SisReservas
{
    
    public partial class O_RUTA : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public Nullable<decimal> ID_RUTA
        {
            get { return _iD_RUTA; }
            set
            {
                if (_iD_RUTA != value)
                {
                    OnComplexPropertyChanging();
                    _iD_RUTA = value;
                    OnPropertyChanged("ID_RUTA");
                }
            }
        }
        private Nullable<decimal> _iD_RUTA;
    
        [DataMember]
        public Nullable<decimal> ID_CIUDAD_ORIGEN
        {
            get { return _iD_CIUDAD_ORIGEN; }
            set
            {
                if (_iD_CIUDAD_ORIGEN != value)
                {
                    OnComplexPropertyChanging();
                    _iD_CIUDAD_ORIGEN = value;
                    OnPropertyChanged("ID_CIUDAD_ORIGEN");
                }
            }
        }
        private Nullable<decimal> _iD_CIUDAD_ORIGEN;
    
        [DataMember]
        public Nullable<decimal> ID_CIUDAD_DESTINO
        {
            get { return _iD_CIUDAD_DESTINO; }
            set
            {
                if (_iD_CIUDAD_DESTINO != value)
                {
                    OnComplexPropertyChanging();
                    _iD_CIUDAD_DESTINO = value;
                    OnPropertyChanged("ID_CIUDAD_DESTINO");
                }
            }
        }
        private Nullable<decimal> _iD_CIUDAD_DESTINO;
    
        [DataMember]
        public Nullable<decimal> ID_FLOTA
        {
            get { return _iD_FLOTA; }
            set
            {
                if (_iD_FLOTA != value)
                {
                    OnComplexPropertyChanging();
                    _iD_FLOTA = value;
                    OnPropertyChanged("ID_FLOTA");
                }
            }
        }
        private Nullable<decimal> _iD_FLOTA;
    
        [DataMember]
        public Nullable<decimal> ID_HORARIO
        {
            get { return _iD_HORARIO; }
            set
            {
                if (_iD_HORARIO != value)
                {
                    OnComplexPropertyChanging();
                    _iD_HORARIO = value;
                    OnPropertyChanged("ID_HORARIO");
                }
            }
        }
        private Nullable<decimal> _iD_HORARIO;
    
        [DataMember]
        public Nullable<decimal> ID_PRECIO
        {
            get { return _iD_PRECIO; }
            set
            {
                if (_iD_PRECIO != value)
                {
                    OnComplexPropertyChanging();
                    _iD_PRECIO = value;
                    OnPropertyChanged("ID_PRECIO");
                }
            }
        }
        private Nullable<decimal> _iD_PRECIO;
    
        [DataMember]
        public Nullable<decimal> ID_CONDUCTOR
        {
            get { return _iD_CONDUCTOR; }
            set
            {
                if (_iD_CONDUCTOR != value)
                {
                    OnComplexPropertyChanging();
                    _iD_CONDUCTOR = value;
                    OnPropertyChanged("ID_CONDUCTOR");
                }
            }
        }
        private Nullable<decimal> _iD_CONDUCTOR;

        #endregion

        #region Propiedades complejas
    
        [DataMember]
        public O_DATOS_AUD O_DATOS_AUD
        {
            get
            {
                if (!_o_DATOS_AUDInitialized && _o_DATOS_AUD == null)
                {
                    _o_DATOS_AUD = new O_DATOS_AUD();
                    ((INotifyComplexPropertyChanging)_o_DATOS_AUD).ComplexPropertyChanging += HandleComplexPropertyChanging;
                }
                _o_DATOS_AUDInitialized = true;
                return _o_DATOS_AUD;
            }
            set
            {
                _o_DATOS_AUDInitialized = true;
                if (!Equals(_o_DATOS_AUD, value))
                {
                    if (_o_DATOS_AUD != null)
                    {
                        ((INotifyComplexPropertyChanging)_o_DATOS_AUD).ComplexPropertyChanging -= HandleComplexPropertyChanging;
                    }
    
                    OnComplexPropertyChanging();
                    _o_DATOS_AUD = value;
                    OnPropertyChanged("O_DATOS_AUD");
    
                    if (value != null)
                    {
                        ((INotifyComplexPropertyChanging)value).ComplexPropertyChanging += HandleComplexPropertyChanging;
                    }
                }
            }
        }
        private O_DATOS_AUD _o_DATOS_AUD;
        private bool _o_DATOS_AUDInitialized;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        private void HandleComplexPropertyChanging(object sender, EventArgs args)
        {
            // Enviar el evento a todas las escuchas porque algo ha cambiado en una propiedad compleja anidada
            OnComplexPropertyChanging();
        }
    
        public static void RecordComplexOriginalValues(String parentPropertyName, O_RUTA complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("El parámetro de cadena no puede ser NULL ni estar vacío.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_RUTA", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_RUTA);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_CIUDAD_ORIGEN", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_CIUDAD_ORIGEN);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_CIUDAD_DESTINO", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_CIUDAD_DESTINO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_FLOTA", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_FLOTA);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_HORARIO", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_HORARIO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_PRECIO", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_PRECIO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ID_CONDUCTOR", parentPropertyName), complexObject == null ? null : (object)complexObject.ID_CONDUCTOR);
            O_DATOS_AUD.RecordComplexOriginalValues(String.Format(CultureInfo.InvariantCulture, "{0}.O_DATOS_AUD", parentPropertyName), complexObject == null ? null : complexObject.O_DATOS_AUD, changeTracker);
        }

        #endregion

    }
}
